---
title: "GDPR notes from Institutions"
author: "Andrea Seisler"
date: "`r Sys.time()`"
output:
  github_document: default
  html_document:
    self-contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Questions and Concerns from EU Institutions regarding GDPR

### Queen's University Belfast  

In order for this to be compliant with our obligations under GDPR the explicit consent of the data subject will be required.  We do not normally rely on consent, but to enable the international restricted transfer of data as Databrary is based in the US and not covered by Privacy Shield. 


Consent is defined in Article 4(11) GDPR as:

“any freely given, specific, informed and unambiguous indication of the data subject’s wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her”.

Article 7 also sets out further ‘conditions’ for consent, with specific provisions on:

- keeping records to demonstrate consent;
- prominence and clarity of consent requests;
- the right to withdraw consent easily and at any time; and
- freely given consent if a contract is conditional on consent.
 
In relation to the restricted transfer the data subject would need to be give precise details about the transfer and the possible risks of making a transfer to a country that does not have provide adequate protection for personal data and without any other appropriate safeguards in place i.e. if Databrary were to sign up to the Standard Contractual Clauses.  

 

My main concern would be how to manage consent?  How can personal data be removed?  Who will be responsible for this? 

 

If Jocelyn is purely accessing information and not uploading I see no issue.

[Standard contractual clauses for data transfers between EU and non-EU  countries](https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en)


### University of Manchester

I do not, obviously, know anything about the research project involved or about the nature and extent of the data being collected, but these measures would usually be along the lines of:
- Has the project received appropriate ethical approval?  
- Has the researcher undertaken appropriate Data protection training?  
- Has the researcher completed a Data Management Plan?  
- Are the data subjects aware of this use of their data and their rights under European law? (There may be ways around this one, but we would need to know details of the project before we could advise)
- Will we be a data controller or data processor for this data?  
- Is there any special category data involved?  

In summary, I don’t think that there is any bar to us signing this agreement in a data protection context, but we would need to be sure that the appropriate internal work had been done before we could receive and start using the data.

### University of Leeds

Under GDPR we cannot agree to accept the HIPAA code of conduct in relation to the work we are proposing to make available unless Databrary (possibly under HIPAA obligations) is compliant with the ‘Privacy Shield’ level of operation – if so then we may be able to transfer the recording’s subject to any further use of those recordings being compliant with the Privacy Shield Framework. This would mean that any organisation/body wishing to access the recording’s from thereon would also have to agree that they operate and are wholly compliant with the Privacy Shield Framework. See: https://www.privacyshield.gov/welcome

If any body was not compliant then we would need to ask them to sign the attached GDPR standard terms, unequivocally.

Is it possible to accommodate this at all? We were hoping that a way around this could be by adding a disclaimer on the Databrary site that access to such recordings could only be granted after accession to the attached GDPR document, or solid confirmation that that body was compliant with the Privacy Shield Framework.



### University of Edinburgh

Our legal team at the University of Edinburgh has expressed serious concerns about the transfer of our data to Databrary, due largely to the nature of the data we intend to submit (videos of participants in an experiment, who are anonymous but potentially recognisable) and also, if I understand it correctly, to the fact that, outside Privacy Shield, the US is not recognised as a country providing fully adequate data protection by GDPR standards. 


### University of Warwick

1. We do not, as a policy sign up to contracts with a hold harmless provision.  

I would require the term “and renders harmless” to be removed from the contract

2. We usually require a two way indemnity and in any event that indemnity is usually capped (below is the language we use)

  - X1. The aggregate liability of each Party in connection with this Agreement or the subject matter hereof (whether arising in contract, tort (including negligence) or otherwise) shall be limited to ten thousand pounds sterling (£10,000).  

  - X2. Subject to clause X3 neither Party shall be liable to the other Party for any indirect, consequential or special damages or losses, or any loss of profits, loss of revenue (other than revenue due under this Agreement or any other agreement entered into between the Parties) which   arises directly or indirectly from that Party’s breach or non-performance of this Agreement, or negligence in the performance of this Agreement or from any liability arising in any other way out of the subject matter of this Agreement even if the Party bringing the claim has advised the other Party of the possibility of those losses arising, or if such losses were within the contemplation of the Parties.  

  - X3. Nothing in this Agreement limits or excludes either Party’s liability for:  
      - X3.1 death or personal injury caused by negligence; or
      - X3.2 fraud or for any other type of liability that, by law, cannot be limited or excluded.  
      - X3.3 Breach of relevant data protection legislation  

3. Photographs are definitely personal data, so we would need reassurance that the data we are receiving the data is GDPR-compliant. ( general Data Protection Regulation) , There doesn’t appear to be any confirmations in here about the legal basis or authority for sharing the images. Do you  provide any information or have a policy about GDPR compliance when providing images to users in Europe?

### University of Giessen  

In Europe, we now have a new data protection regime which makes such agreements a little bit more complicated. For example, in our data protection agreements we have to make sure that data will be deleted, for example in 10 or 15 years. As far as I understood databarary, the data won't be deleted. This could be a problem. So, we will further work on the issues and then let you know.

### Vrije Universiteit Amsterdam

Comments on Ethical Data Sharing under the GDPR
Summary by Jessica Hrudey, Research Data Officer for Faculty of Behavioural and Human Movement Sciences at the VU
Advise sought from Privacy Lawyers from Administrative Affairs at the VU  

•	As a starting point, I think we need more clarity regarding how the “[participant-rights.md](participant-rights.md)” document will be applied. Is this intended to a standalone template for an information letter and informed consent form or is the intention that the text will be added to an existing information letter and informed consent form?  
o	The reason that I ask this, is that it helps to define: a) who the party is that is obtaining consent and b) what information needs to be present to meet GDPR requirements.   
o	The privacy lawyers at our institution immediately questioned this, which is why they state the following:
“Transparency
 
When the GDPR applies, all of the information mentioned in articles 13 and 14 GDPR should be provided to the participants. Article 13 GDPR applies when personal data are collected from the data subject (for example by a researcher contributing to Databrary). Article 14 GDPR applies when personal data are not obtained from the data subject (for example when Databrary obtains personal data from a researcher, or when a researcher of commercial organization subsequently obtains personal data from Databrary).  
 
Much of the information required by articles 13 and 14 GDPR is currently missing in the templates, such as:  
•	Identity of the controller  
•	Recipients of the personal data  
•	Source of the personal data (in case article 14 GDPR applies)  
•	Storage period (the storage period may not be indefinite)  
•	Information regarding safeguards with respect to transfers of personal data from countries within the European Economic Area (EEA) to countries outside the EEA (see our comments on ‘International Data Transfers’ below)  
•	Rights of data subjects (such as access, rectification, restriction, complaints, etc.)  
 
Note that the information mentioned in article 13 GDPR should be provided to participants at the time when personal data are collected. We anticipate that the main challenge with respect to article 13 GDPR will be (for the researcher contributing to Databrary) to provide transparency regarding the recipients of personal data and the safeguards with respect to international data transfers.
 
Next, the information mentioned in article 14 GDPR should be provided “within a reasonable period after obtaining the personal data, but at the latest within one month” (article 14(3)(a) GDPR). We anticipate that the transparency obligations under article 14 GDPR will be especially difficult to meet in the ‘Databrary landscape’, because parties subject to these obligations (both Databrary itself and researchers and companies accessing Databrary) will operate in the background - and as such it will be very difficult for them to provide said information to participants.
 
For your information, note that the EU data protection authorities have issued [guidelines on transparency under the GDPR](https://www.autoriteitpersoonsgegevens.nl/sites/default/files/atoms/files/guidelines_on_transparency.pdf) in which they explain which information should be provided as a minimum in their view. Please refer to these guidelines in order to get a better understanding of the transparency requirements. The table on the last pages of the guidelines (pages 36 – 40) is especially helpful in our view. 
 
Consent
 
When the GDPR applies, consent should meet the conditions set out by the GDPR (articles 4(11) and 7-9 GDPR). Again, the EU data protection authorities have published guidelines on this topic. In their [guidelines on consent under the GDPR](https://www.autoriteitpersoonsgegevens.nl/sites/default/files/atoms/files/guidelines_on_consent.pdf), they explain among other things what the minimum content requirements are for consent to be “informed” (in the sense of article 4(11) GDPR). In short, these include (page 13): 

•	The controller’s identity  
•	The purpose of each of the processing operations for which consent is sought (when there are multiple purposes, the participant should be able to provide separate consent for each purpose)  
•	What (type of) data will be collected and used  
•	The existence of the right to withdraw consent (and how to do this)
•	Information about the use of the data for automated decision-making in accordance with article 22(2)(c) GDPR where relevant, and  
•	On the possible risks of data transfers due to absence of an adequacy decision and of appropriate safeguards as described in article 46 GDPR  
 
Much of this information is currently missing in the templates. Please note that, in order to obtain “informed” consent, it is not required to provide all of the information mentioned in articles 13 and 14 GDPR. However, note that such information should be provided by the controller elsewhere (for example in a privacy notice/statement), and the participants should be referred to such information when they are asked to consent (for example by means of a hyperlink).”

•	Ultimately, if the aim is that this document is intended to supplement existing information letters and informed consent forms, then some of the commentary above is not applicable, as the researcher using your template is responsible for informing the participants of this information. At the same time, solutions to keep participants informed of new uses (i.e. when a secondary user obtains and uses the data for new purposes) according to article 14 need to be worked out prior to the use of such a template. I gather that the intention of your markdown document is to create standard language for sharing video data regardless of which data repository will be used. However, prior to the use of such a template with such a broad scope, several issues need to be sorted before the text can be used in information letters and informed consent forms. It may be necessary to have a set of instructions for use of the template text, as well as conditions that need to be met before the template can be used (for example, methods for how the secondary users can meet their obligations under the GDPR, specifically, how will they inform data subjects about new use of the data). The conditions that need to be addressed are discussed further below.  

•	Both the privacy lawyers and myself are curious how the data repository will be positioned under the GDPR, i.e. is the intention here that the repository is also a controller? 
    - Our lawyers said:  
“Allocating GDPR responsibilities in the Databrary landscape  
 
When overlooking the ‘Databrary landscape’ including all of the parties contributing to it and accessing its digital library, perhaps the most important and difficult matter in respect of the GDPR is to allocate how these parties can meet their obligations under the GDPR. In order to the challenges at stake, it is at first vital to differentiate between the ‘roles’ parties can have under the GDPR:  

•	Controller: a party which “determines the purposes and means of the processing of personal data” (art. 4(7) GDPR)  

•	Processor: a party which “processes personal data on behalf of the controller” (art. 4(8) GDPR)  
 
Given the purposes of processing, and especially taking into account the responsibility of Databrary to accept and review proposals from commercial entities for access to personal data (as described in the Research Participants’ Rights template), we anticipate that all parties involved (Databrary, parties contributing to Databrary and parties accessing Databrary) will qualify as ‘controllers’ under the GDPR. This means that all of these parties are required to meet all of the obligations under the GDPR (unlike processors, which only have to meet certain obligations under the GDPR). Since participants will first and foremost be in contact with the researcher contributing to Databrary, it will in practice be very difficult for the other parties (who are operating in the ‘background’ for the participants) to meet, for example, their transparency obligations under the GDPR.”  

•	Therefore, it needs to be clarified exactly what role the data repository will play in the relationship. It is confusing in the current text of the markdown document, because it does seem that the repository is responsible for deciding who gets access. In general, my experience in Europe is that repositories function solely as processors: they ensure that the data are maintained indefinitely, but they play no role is deciding who gets access. So that is something that needs to be decided upon and made clear. If the intention is that the markdown template is meant to be applied to any appropriate repository, then it opens the door to even more complexities, since some repositories may want to have a controller status and others a processor status.  

•	The transparency issues for secondary users have been discussed above (regarding the requirements of article 14). As already stated, this is something this needs to be addressed prior to the use of the markdown text in information letters and ICFs.  

•	The last main technical issue that our lawyers were concerned about is the nature of data sharing outside the EEA. They write:
“International data transfers  
 
Transfers of personal data from the EEA to the US (and any other countries outside the EEA) should meet the conditions set out by the GDPR. One way to comply with these conditions is to conclude Standard Contractual Clauses between Databrary and each party contributing to and accessing its library (insofar the GDPR applies). This would require a lot of complex contracting efforts. Another way to legitimize transfers from the EEA to Databrary’s repository in the US would be for Databrary to self-certify under the [EU – US Privacy Shield Framework](https://www.privacyshield.gov/welcome). With such certification in place, there is no need for Databrary to conclude Standard Contractual Clauses with parties located in the EEA transferring personal data to it in the US. However, such certification will not legitimize further transfer of these personal data to parties subsequently accessing these personal data. For more information on international data transfers, please refer to the [website of the European Commission](https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection_en).”  

•	In their assessment of the text, our lawyers focused on the relationship between the original data collector/controller and specifically Databrary as the sole possible repository. If the intention is that this template could be used with other repositories, then the above issues need also need to be addressed, and the issues to sort out will vary depending on the country that the repository is located in.   

•	In addition to addressing what kind of agreement needs to be in place between the original data collector and the repository, systems need to be in place for setting up data sharing agreements between the original data collector and the secondary users. Because ultimately under the GDPR the original collector is still responsible for the data, so they are the ones who need to be signing these agreements with secondary users.  

•	This is addressed somewhat in the sections “Who will have access to your data?” and “Permission to permit commercial uses”, but the process isn’t quite clear at the moment. It seems that for research, educational, charitable purposes the agreements are made between the original data collector {HOST INSTITUTION} and the re-user; but that for commercial purposes databrary.org makes the decision about whether the data can be accessed for commercial use. Is that the intention here?  
    o	Also, we need to consider how much detail should be included here with regards to the legal agreements between the HOST INSTITUTION and the re-user. If the HOST INSTITUTION deposited data that is protected by the GDPR and the re-user is located outside the EEA, we need to have protections in place, most likely through the European Commission’s standard contractual clauses. I don’t think that level of detail is necessarily required for the text of the template, but this would need to be addressed in the instructions for the user of the template  
    o	Can any registered user access any data, or is the intention that each registered user needs permission from the original depositor to get access to the data; the way this section is written is currently not quite clear?  
    	Also, it’s not quite clear what is meant with “To gain access, a user must apply for sponsorship and receive approval from an academic … institution”. So, the procedure for gaining access would be to be approved by an institution who will be responsible for your actions, and that this institution must already have a legal contract with the original depositor of the data? And once a user has been approved by their own institution, they can access the data? I don’t think that’s how the process is intended to go, but this is how it seems to be described.   
    o	Furthermore, regarding commercial uses, if the uses are determined in advance, then these pre-determined uses should be described to the participants, so they can be informed in deciding whether or not to consent to this; this could be a section that the user of the template could fill in with specifics.   

In addition to the points addressed above, there are a few more specific concerns in the text that I think could be addressed so that it’s more in line with GDPR requirements. Overall, there tends to be a lot of broad statements, so either there should be some guidance for those using the template regarding where the text can be adjusted. For example:  

•	under section “Permission to show segments” it is not entirely clear in which situations recordings will be made to the public via a platform such as YouTube. That’s a major concern, because it needs to clear to the individual where exactly the data are ending up. The text seems to just say, this could happen, but participants need to know more. This could be something that a user of the template could modify based on whether or not they intend to allow this to happen (if the video segments won’t be used in presentations, then perhaps the risk of the video’s showing up on YouTube is not there).   

•	Furthermore, in the section “Permission to show segments” there is a fair bit of generalization. For example, talking about the various possible situations (“We may also request separate permission) leads to confusion and lack of clarity for the individual. So, this would be a section that a user of this template could change based on whether they are going to ask for consent to show segments or not. Furthermore, if segments will be shared it needs to be defined as to WHICH segments will be shared and what kind of information is included in said fragment. (Note that in the original Databrary.org data [release template](https://www.databrary.org/resources/templates/release-template.html) about trusting researchers judgement about excerpts (and thus what could end up on YouTube), will unfortunately not hold up against the GDPR. Everything needs to be specific in the GDPR and the participant needs to have all the power so they need to know what exactly could end up on YouTube (or elsewhere)).  

•	under section “What personal data will be stored and shared?”, again we miss specificity here. “Information supplied by authorized users of {REPOSITORY} is too vague, so this needs to be a section that a user of the template must modify to include specifics. Also, it’s not quite clear for the template user as to what is meant by “information supplied by authorized users of {NAME OF REPOSITORY} who analyze data you (or your child) provide”: isn’t it the original researcher (the original collector of data or host institution) who is providing all of the data, not other re-users of data. I think much of this section demonstrates that it is currently not clear who is going to use this template and subsequently who will present this information to the participant. I think the researcher (a.k.a. the original collector of data or host institution) is most suited to pose this information and so the text should be written from that viewpoint. At the moment, it seems to be partly from the viewpoint of the repository, which seems less appropriate.  

•	under section “How will my personal data be used?”, I would add an “only” before the list of purposes (educational, scientific etc). It should be clear to participants that the data will not be re-used for business or advertising purposes (unless consent is obtained specifically for those purposes). Users of the template should also have the option to take out the sections on asking consent for business/advertising purposes if the user feels this is inappropriate to ask of their participants and there is no intention for data to be used for those purposes.  
    o	Note that this section also goes back to the issues addressed above regarding how to inform participants about new uses. This is a complex under the GDPR and the links provided by our privacy lawyers give some guidance. It is advised that, although research purposes are considered compatible with the original purposes, as the specifics about the research purposes become clear, the subjects need to be informed about these specifics. But at the same time, the secondary users should not try to identify the subjects solely for the purposes of informing them about these new uses (a bit of a catch-22). Secondary users could potentially provide information in the form of a privacy statement on a webpage, stating that they used data from Databrary with DOI ABCDE, but there needs to be more infrastructure in place so that data subjects know where to find this information. Perhaps through a landing page from the repository, where the data are described, there could also be information about the contact information for secondary users so that participants can contact them for more info about secondary uses. This would of course require active updating of the dataset landing page. This is definitely a long-term issue and more infrastructural planning needs to be sorted out, not just for Databrary, but for all repository systems.  
    o	There may be the potential for using terms of use, where the secondary users may only re-use the data for purposes that were pre-defined by the host institution (original data collector), and therefore described to the participants in the information letter, but that may limit the value of the data.  

•	The following sentence under section “Who will have access to your personal data?” is a bit confusing: “The institution applying for access to personal data on {NAME OF REPOSITORY} must agree that your decision about whether to share your personal data or not must be respected, and that all regulations and laws that relate to the processing of personal data where your personal data were collected must be followed” If the data are in the repository, then the individuals have agreed to the data being there and being re-used. It is unclear what the secondary user must agree with here. If someone has not given consent for re-use of their data, wouldn’t the data not be in repository? And I would think that ultimately, the original depositor decides if the secondary user gets access or not anyway.  

•	Under the section “What if I change my mind?”, I think this section is quite good. It can go into more detail, however, about risks. I would expand on the last sentence about being unable to guarantee the destruction of all copies. It may also be necessary to include more detail in earlier sections of this template regarding secondary users and security because the main issue is: once these data are shared, it’s going to be very hard to be certain that they aren’t re-shared AND we cannot know for sure if security measures/data laws in certain countries are an issue. Ultimately, there needs to be more detail about the risks: that once data are shared there is no guarantee that all copies can be deleted at a later stage; data will be shared with any and all countries regardless of the privacy laws and security measures assured by those countries (in the interest of open science because it’s not fair to exclude researchers from certain countries just because a given country may have a bad rap), but that the secondary users do need to provide assurances of their security measures.  
    o	A lot of these concerns above are addressed somewhat in section “Risks of sharing personal data”, however, it mostly mentions the measures that will be applied to reduce risks and we need to be clear that the risk can never be reduced to 0. There is always a risk that a secondary user won’t be careful enough, or won’t abide with the terms of use/data sharing agreement. We aren’t going to have any ways to check that people are abiding with agreements unless something goes wrong (i.e. data are re-shared inappropriately by the user) at which point the data have already been leaked. So, it needs to be clear that there is always a risk with the sharing of these types of data and that we take measures to reduce the risk, but no measure is 100% effective  
    o	I think what is stated in the Databrary.org release template is stronger, under the section “How long will information remain in the library?” because in the template it states that information previously shared cannot be retrieved. We can still aim to try and retrieve and destroy the data, but there is always a risk that the data has been shared beyond our ability to track it down and destroy it.  

•	Under “Citizens of the EU”, again the generalized nature of the text makes it confusing. If the data are in fact stored outside the EU and the data don’t belong to EU residents, then the EU laws don’t apply, but if data are stored within the EU or the data belongs to EU residents, then these laws do apply. It depends on the repository in question and the research team using the template would have to modify the text to suit the situation. Hence the need for good instructions.  

•	“Benefits of sharing data” can be expanded upon: what are the specific benefits to participants, e.g. if data are re-used the participant won’t have to be repeatedly contacted for similar research again and again, this pdf from Stanford has a nice summary of a study done on this topic: (http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/ethics/h2020_hi_ethics-self-assess_en.pdf)  

•	In the databrary.org release template, I’m not sure I would give a script to the researchers. I guess it depends on the institution and the researcher, but perhaps instead of a script you could list the talking points that need to be addressed with the participants after the recording is complete, so that they are fully informed about what sharing the video means.  



