---
title: "Research Participants' Rights"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preamble

As a research participant, you have a fundamental right to control your personal data and how it is processed.
The processing or analysis of your personal data can and should serve the interests of humankind.

This statement of research participant rights is meant to provide information to you about how sharing your personal data with other researchers via electronic data libraries can be done in a way that protects your rights, your confidentiality, and your privacy, while serving the greater good.
You may choose to share your data or not to share.
We ask your permission to share your data because we think that this will lead to faster progress in research on human development, health, and behavior.

## What we ask of you

We ask your permission to store and share personal data about you (and your child) in a secure, web-based data library called {NAME OF REPOSITORY}, hosted at {HOSTING INSTITUTION} in {COUNTRY}.
We ask your permission to store and share these personal data for an indefinite period in a secure location so that future authorized users of {NAME OF REPOSITORY} can access the data.

## Permission to show segments to the public

If you agree to share your personal data, we may also request separate permission to allow authorized users of {NAME OF REPOSITORY} to show selected images or segments in scientific or classroom presentations for informational and educational purposes.
Some scientific or classroom presentations may be recorded, and these recordings may then be made available to the public via the internet (e.g., YouTube).
Giving permission for segments to be shown does not give permission for the recordings themselves to be distributed to the public.

## What personal data will be stored and shared?

Personal data stored about you (or your child) on {NAME OF REPOSITORY} may include video or audio recordings, photographs, and images; other information such as age, birth date, sex, race, ethnicity, education, and self-reported health information; and information supplied by researchers or clinicians who analyze data from this session.

However, no information will be included in {NAME OF REPOSITORY} about how to contact you or your family.
No data files stored on {NAME OF REPOSITORY} will be identified by your (or your child's) name, address, phone number, email address or similar information that would make it easy to identify you (or your child) or contact you (or your child).
Instead, all data files will be identified by a code number.
The use of code numbers is intended to make it harder for another person to identify you (or your child).

## How will my personal data be used?

We ask your permission to allow your (or your child's ) personal data to be used for educational, scientific, health-related, and charitable purposes, including purposes beyond the scope of this particular study.
We ask for your permission for this broad set of uses because we want to maximize the possiblity that your data (or your child's) can serve valuable and important public purposes in the future, and we cannot envision today all possible ways shared personal data like yours might be valuable in the future.
Please note that any uses of your personal data must be reviewed and approved by people whose job is to ensure that your personal data are not misused and that you are not harmed.

## Who will have access to your personal data?

{NAME OF REPOSITORY} permits only authorized users to have access to personal data from research participants like you (and your child).
To gain access, a user must apply for sponsorship and receive approval from an academic, not-for-profit, research, government, health, (or commercial) institution.
The institution must sign a legal contract with {HOST INSTITUTION} covering how personal data may be used and how personal data must be protected.
The institution requesting access for a user must promise to take responsibility for the actions of any user it approves related to the use of your personal data.
The institution must promise that any user it approves has training in how to protect personal data and how to conduct research that does not harm research participants.
The institution agrees that your decision about whether to share your personal data must be respected, and that all regulations and laws that relate to the processing of personal data must be followed.

## What if I say no?

You do not have to give permission to share your information with {NAME OF REPOSITORY}. 
You may give permission to share your data with {NAME OF REPOSITORY} but refuse permission to allow images or segments to be shown in scientific or classroom presentations.
None of your choices will affect receipt of payment if offered for participation in this or future studies. 

## What if I change my mind?

You may revoke your permission to store and share data in {NAME OF REPOSITORY} at any time.
To do so, you must contact the person who enrolled you in this study at {CONTACT INFO FOR RESEARCHER}.
{RESEARCHER} knows the code number used for your personal data and has the power to remove your data from {NAME OF REPOSITORY} or request that {NAME OF REPOSITORY} remove it.

If a long time has passed between the time that you participated in this study and the time you change your mind about wanting to continue sharing your data, it may be difficult or impossible to contact {RESEARCHER}.
The information linking your identity to the code number may have been destroyed in order to protect your confidentiality.
You may have to contact {NAME OF REPOSITORY} yourself at {REPOSITORY CONTACT INFO} and provide personal information that would allow {NAME OF REPOSITORY} to determine what data files need to be removed.

If {NAME OF REPOSITORY} is requested to remove specific data files, it will do so to the best of its ability and request that all copies of the data files are also removed.

## Citizens of the European Union (EU)

If you are a citizen of the European Union (EU), please note that storing data in {NAME OF REPOSITORY} means your personal data may be stored outside of the EU.
{NAME OF REPOSITORY} is not subject to the laws of the EU concerning the protection of personal data, but the policies and practices of {NAME OF REPOSITORY} are intended to protect your personal data in ways similar to EU laws like the General Data Protection Regulation (GDPR).

## Risks of sharing data

If you agree to share photographs, video, or audio recordings with {NAME OF REPOSITORY}, images and/or sounds of you or other people in the recordings may be seen or heard by other people who have access to the {NAME OF REPOSITORY}
First and/or last names of you or other people may be spoken aloud. 
If the study takes place in your home, aspects of your home may be seen or heard, or things you said may be recorded. 
In addition, other information may have been collected about you, your child, or your family in conjunction with this session and shared in {NAME OF REPOSITORY} along with any photographs, video, or audio recordings.
Thus, it is possible that someone with access to {NAME OF REPOSITORY} might be able to identify you, your child, or other people in the recordings.
But every person who is approved to have access to {NAME OF REPOSITORY} must promised not to reveal the identities of any person they observe in a recording.
Every person also promises not to contact any person they recognize or to otherwise reveal information that could embarrass or harm that person. 
Also, every person who is approved to have access to {NAME OF REPOSITORY} must promise not to share images or recordings of any person with anyone outside of {NAME OF REPOSITORY} unless they have explicit permission to do so.

## Benefits of sharing data 

Data repositories like {NAME OF REPOSITORY} allow researchers to share data with one another for educational, scientific, health-related, and charitable purposes.
Data sharing accelerates progress in research, and it makes findings from scientific studies more robust and reliable.
This benefits the public as a whole.
Data sharing also increases the benefits of participating in research to you and to others.
